language: java
branches:
  only:
    - develop
    - /^release-[0-999].[0-999]$/
    - master
notifications:
  email:
    recipients:
      - gusguma@gmail.com
script:
  #Test unitario y de integracion con cobertura
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  #SONARCLOUD
  - mvn verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=gusguma-github -Dsonar.login=$SONAR

#Deploy https://template-microservice-user.herokuapp.com
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU
  on:
    branch: master


